In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
dir(sql)

['Binary',
 'Blob',
 'Connection',
 'Cursor',
 'DataError',
 'DatabaseError',
 'Date',
 'DateFromTicks',
 'Error',
 'IntegrityError',
 'InterfaceError',
 'InternalError',
 'LEGACY_TRANSACTION_CONTROL',
 'NotSupportedError',
 'OperationalError',
 'PARSE_COLNAMES',
 'PARSE_DECLTYPES',
 'PrepareProtocol',
 'ProgrammingError',
 'Row',
 'SQLITE_ABORT',
 'SQLITE_ABORT_ROLLBACK',
 'SQLITE_ALTER_TABLE',
 'SQLITE_ANALYZE',
 'SQLITE_ATTACH',
 'SQLITE_AUTH',
 'SQLITE_AUTH_USER',
 'SQLITE_BUSY',
 'SQLITE_BUSY_RECOVERY',
 'SQLITE_BUSY_SNAPSHOT',
 'SQLITE_BUSY_TIMEOUT',
 'SQLITE_CANTOPEN',
 'SQLITE_CANTOPEN_CONVPATH',
 'SQLITE_CANTOPEN_DIRTYWAL',
 'SQLITE_CANTOPEN_FULLPATH',
 'SQLITE_CANTOPEN_ISDIR',
 'SQLITE_CANTOPEN_NOTEMPDIR',
 'SQLITE_CANTOPEN_SYMLINK',
 'SQLITE_CONSTRAINT',
 'SQLITE_CONSTRAINT_CHECK',
 'SQLITE_CONSTRAINT_COMMITHOOK',
 'SQLITE_CONSTRAINT_FOREIGNKEY',
 'SQLITE_CONSTRAINT_FUNCTION',
 'SQLITE_CONSTRAINT_NOTNULL',
 'SQLITE_CONSTRAINT_PINNED',
 'SQLITE_CONSTRAINT_PRIMARYKEY',
 'SQLITE_CONSTRAINT_ROWID',
 'SQLITE_CONSTRAINT_TRIGGER',
 'SQLITE_CONSTRAINT_UNIQUE',
 'SQLITE_CONSTRAINT_VTAB',
 'SQLITE_CORRUPT',
 'SQLITE_CORRUPT_INDEX',
 'SQLITE_CORRUPT_SEQUENCE',
 'SQLITE_CORRUPT_VTAB',
 'SQLITE_CREATE_INDEX',
 'SQLITE_CREATE_TABLE',
 'SQLITE_CREATE_TEMP_INDEX',
 'SQLITE_CREATE_TEMP_TABLE',
 'SQLITE_CREATE_TEMP_TRIGGER',
 'SQLITE_CREATE_TEMP_VIEW',
 'SQLITE_CREATE_TRIGGER',
 'SQLITE_CREATE_VIEW',
 'SQLITE_CREATE_VTABLE',
 'SQLITE_DBCONFIG_DEFENSIVE',
 'SQLITE_DBCONFIG_DQS_DDL',
 'SQLITE_DBCONFIG_DQS_DML',
 'SQLITE_DBCONFIG_ENABLE_FKEY',
 'SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER',
 'SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION',
 'SQLITE_DBCONFIG_ENABLE_QPSG',
 'SQLITE_DBCONFIG_ENABLE_TRIGGER',
 'SQLITE_DBCONFIG_ENABLE_VIEW',
 'SQLITE_DBCONFIG_LEGACY_ALTER_TABLE',
 'SQLITE_DBCONFIG_LEGACY_FILE_FORMAT',
 'SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE',
 'SQLITE_DBCONFIG_RESET_DATABASE',
 'SQLITE_DBCONFIG_TRIGGER_EQP',
 'SQLITE_DBCONFIG_TRUSTED_SCHEMA',
 'SQLITE_DBCONFIG_WRITABLE_SCHEMA',
 'SQLITE_DELETE',
 'SQLITE_DENY',
 'SQLITE_DETACH',
 'SQLITE_DONE',
 'SQLITE_DROP_INDEX',
 'SQLITE_DROP_TABLE',
 'SQLITE_DROP_TEMP_INDEX',
 'SQLITE_DROP_TEMP_TABLE',
 'SQLITE_DROP_TEMP_TRIGGER',
 'SQLITE_DROP_TEMP_VIEW',
 'SQLITE_DROP_TRIGGER',
 'SQLITE_DROP_VIEW',
 'SQLITE_DROP_VTABLE',
 'SQLITE_EMPTY',
 'SQLITE_ERROR',
 'SQLITE_ERROR_MISSING_COLLSEQ',
 'SQLITE_ERROR_RETRY',
 'SQLITE_ERROR_SNAPSHOT',
 'SQLITE_FORMAT',
 'SQLITE_FULL',
 'SQLITE_FUNCTION',
 'SQLITE_IGNORE',
 'SQLITE_INSERT',
 'SQLITE_INTERNAL',
 'SQLITE_INTERRUPT',
 'SQLITE_IOERR',
 'SQLITE_IOERR_ACCESS',
 'SQLITE_IOERR_AUTH',
 'SQLITE_IOERR_BEGIN_ATOMIC',
 'SQLITE_IOERR_BLOCKED',
 'SQLITE_IOERR_CHECKRESERVEDLOCK',
 'SQLITE_IOERR_CLOSE',
 'SQLITE_IOERR_COMMIT_ATOMIC',
 'SQLITE_IOERR_CONVPATH',
 'SQLITE_IOERR_CORRUPTFS',
 'SQLITE_IOERR_DATA',
 'SQLITE_IOERR_DELETE',
 'SQLITE_IOERR_DELETE_NOENT',
 'SQLITE_IOERR_DIR_CLOSE',
 'SQLITE_IOERR_DIR_FSYNC',
 'SQLITE_IOERR_FSTAT',
 'SQLITE_IOERR_FSYNC',
 'SQLITE_IOERR_GETTEMPPATH',
 'SQLITE_IOERR_LOCK',
 'SQLITE_IOERR_MMAP',
 'SQLITE_IOERR_NOMEM',
 'SQLITE_IOERR_RDLOCK',
 'SQLITE_IOERR_READ',
 'SQLITE_IOERR_ROLLBACK_ATOMIC',
 'SQLITE_IOERR_SEEK',
 'SQLITE_IOERR_SHMLOCK',
 'SQLITE_IOERR_SHMMAP',
 'SQLITE_IOERR_SHMOPEN',
 'SQLITE_IOERR_SHMSIZE',
 'SQLITE_IOERR_SHORT_READ',
 'SQLITE_IOERR_TRUNCATE',
 'SQLITE_IOERR_UNLOCK',
 'SQLITE_IOERR_VNODE',
 'SQLITE_IOERR_WRITE',
 'SQLITE_LIMIT_ATTACHED',
 'SQLITE_LIMIT_COLUMN',
 'SQLITE_LIMIT_COMPOUND_SELECT',
 'SQLITE_LIMIT_EXPR_DEPTH',
 'SQLITE_LIMIT_FUNCTION_ARG',
 'SQLITE_LIMIT_LENGTH',
 'SQLITE_LIMIT_LIKE_PATTERN_LENGTH',
 'SQLITE_LIMIT_SQL_LENGTH',
 'SQLITE_LIMIT_TRIGGER_DEPTH',
 'SQLITE_LIMIT_VARIABLE_NUMBER',
 'SQLITE_LIMIT_VDBE_OP',
 'SQLITE_LIMIT_WORKER_THREADS',
 'SQLITE_LOCKED',
 'SQLITE_LOCKED_SHAREDCACHE',
 'SQLITE_LOCKED_VTAB',
 'SQLITE_MISMATCH',
 'SQLITE_MISUSE',
 'SQLITE_NOLFS',
 'SQLITE_NOMEM',
 'SQLITE_NOTADB',
 'SQLITE_NOTFOUND',
 'SQLITE_NOTICE',
 'SQLITE_NOTICE_RECOVER_ROLLBACK',
 'SQLITE_NOTICE_RECOVER_WAL',
 'SQLITE_OK',
 'SQLITE_OK_LOAD_PERMANENTLY',
 'SQLITE_OK_SYMLINK',
 'SQLITE_PERM',
 'SQLITE_PRAGMA',
 'SQLITE_PROTOCOL',
 'SQLITE_RANGE',
 'SQLITE_READ',
 'SQLITE_READONLY',
 'SQLITE_READONLY_CANTINIT',
 'SQLITE_READONLY_CANTLOCK',
 'SQLITE_READONLY_DBMOVED',
 'SQLITE_READONLY_DIRECTORY',
 'SQLITE_READONLY_RECOVERY',
 'SQLITE_READONLY_ROLLBACK',
 'SQLITE_RECURSIVE',
 'SQLITE_REINDEX',
 'SQLITE_ROW',
 'SQLITE_SAVEPOINT',
 'SQLITE_SCHEMA',
 'SQLITE_SELECT',
 'SQLITE_TOOBIG',
 'SQLITE_TRANSACTION',
 'SQLITE_UPDATE',
 'SQLITE_WARNING',
 'SQLITE_WARNING_AUTOINDEX',
 'Time',
 'TimeFromTicks',
 'Timestamp',
 'TimestampFromTicks',
 'Warning',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_deprecated_names',
 '_deprecated_version',
 '_deprecated_version_info',
 'adapt',
 'adapters',
 'apilevel',
 'collections',
 'complete_statement',
 'connect',
 'converters',
 'datetime',
 'dbapi2',
 'enable_callback_tracebacks',
 'paramstyle',
 'register_adapter',
 'register_converter',
 'sqlite_version',
 'sqlite_version_info',
 'threadsafety',
 'time']

In [3]:
conn = sql.connect('factbook')
conn

In [4]:
'select * from sqllite_master'

'select * from sqllite_master'

In [5]:
pd.read_sql_query('select * from sqlite_master',conn)

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,3,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,facts,facts,47,"CREATE TABLE ""facts"" (""id"" INTEGER PRIMARY KEY..."
2,table,cities,cities,2,CREATE TABLE cities (\n id integer prim...

In [6]:
pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type = 'table'
""", conn)

              name
0  sqlite_sequence
1            facts
2           cities

In [7]:
df = pd.read_sql_query("SELECT * FROM facts", conn)
df

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,1,af,Afghanistan,652230.0,652230.0,0.0,3.256434e+07,2.32,38.57,13.89,1.51
1,2,al,Albania,28748.0,27398.0,1350.0,3.029278e+06,0.30,12.92,6.58,3.30
2,3,ag,Algeria,2381741.0,2381741.0,0.0,3.954217e+07,1.84,23.67,4.31,0.92
3,4,an,Andorra,468.0,468.0,0.0,8.558000e+04,0.12,8.13,6.96,0.00
4,5,ao,Angola,1246700.0,1246700.0,0.0,1.962535e+07,2.78,38.78,11.49,0.46
...,...,...,...,...,...,...,...,...,...,...,...
256,257,zh,Atlantic Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,258,xo,Indian Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,259,zn,Pacific Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,260,oo,Southern Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,261,xx,World,NaN,NaN,NaN,7.256490e+09,1.08,18.60,7.80,NaN

In [9]:
df2 = pd.read_sql_query("SELECT * FROM cities", conn)
df2

      id          name  population  capital facts_id
0      1    Oranjestad       37000        1      216
1      2  Saint John'S       27000        1        6
2      3     Abu Dhabi      942000        1      184
3      4         Dubai     1978000        0      184
4      5       Sharjah      983000        0      184
..   ...           ...         ...      ...      ...
392  393       Mbabane       66000        1      167
393  394         Sanaa     2419000        1      193
394  395          Aden      784000        0      193
395  396        Lusaka     1802000        1      194
396  397        Harare     1542000        1      195

[397 rows x 5 columns]

In [10]:
pd.read_sql_query("SELECT * FROM facts LIMIT 5", conn)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,1,af,Afghanistan,652230,652230,0,32564342,2.32,38.57,13.89,1.51
1,2,al,Albania,28748,27398,1350,3029278,0.30,12.92,6.58,3.30
2,3,ag,Algeria,2381741,2381741,0,39542166,1.84,23.67,4.31,0.92
3,4,an,Andorra,468,468,0,85580,0.12,8.13,6.96,0.00
4,5,ao,Angola,1246700,1246700,0,19625353,2.78,38.78,11.49,0.46

In [11]:
df.head(5)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,1,af,Afghanistan,652230.0,652230.0,0.0,32564342.0,2.32,38.57,13.89,1.51
1,2,al,Albania,28748.0,27398.0,1350.0,3029278.0,0.30,12.92,6.58,3.30
2,3,ag,Algeria,2381741.0,2381741.0,0.0,39542166.0,1.84,23.67,4.31,0.92
3,4,an,Andorra,468.0,468.0,0.0,85580.0,0.12,8.13,6.96,0.00
4,5,ao,Angola,1246700.0,1246700.0,0.0,19625353.0,2.78,38.78,11.49,0.46

In [12]:
df.tail(5)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
256,257,zh,Atlantic Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,258,xo,Indian Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,259,zn,Pacific Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,260,oo,Southern Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,261,xx,World,NaN,NaN,NaN,7.256490e+09,1.08,18.6,7.8,NaN

In [13]:
pd.read_sql_query(
    "SELECT COUNT(*) AS total_rows FROM cities",
    conn
)

   total_rows
0         397

In [14]:
pd.read_sql_query("""
SELECT name, area, population
FROM facts
WHERE area > 5000
""", conn)

                                  name     area  population
0                          Afghanistan   652230  32564342.0
1                              Albania    28748   3029278.0
2                              Algeria  2381741  39542166.0
3                               Angola  1246700  19625353.0
4                            Argentina  2780400  43431886.0
..                                 ...      ...         ...
168     British Indian Ocean Territory    54400         NaN
169  Falkland Islands (Islas Malvinas)    12173      3361.0
170                        Puerto Rico    13791   3598357.0
171                          West Bank     5860   2785366.0
172                     Western Sahara   266000    570866.0

[173 rows x 3 columns]

In [15]:
pd.read_sql_query("""
SELECT cities.name AS capital_name
FROM cities
INNER JOIN facts
ON cities.facts_id = facts.id
WHERE cities.capital = 1
AND facts.death_rate > 2
AND facts.birth_rate < 20
""", conn)

         capital_name
0          Oranjestad
1        Saint John'S
2                Baku
3              Tirana
4             Yerevan
..                ...
123         Road Town
124             Hanoi
125  Charlotte Amalie
126          Windhoek
127          Mata-Utu

[128 rows x 1 columns]

In [16]:
pd.read_sql_query("""
SELECT cities.name AS city_name,
       facts.population_growth
FROM cities
INNER JOIN facts
ON cities.facts_id = facts.id
WHERE facts.population_growth BETWEEN 1 AND 5
ORDER BY facts.population_growth DESC
""", conn)

     city_name  population_growth
0         Juba               4.02
1     Lilongwe               3.32
2    Bujumbura               3.28
3       Niamey               3.25
4      Kampala               3.24
..         ...                ...
210        Fes               1.00
211  Marrakech               1.00
212    Tangier               1.00
213     Agadir               1.00
214    Managua               1.00

[215 rows x 2 columns]

In [17]:
pd.read_sql_query("""
SELECT facts.name AS country_name,
       cities.name AS city_name
FROM facts
LEFT JOIN cities
ON facts.id = cities.facts_id
WHERE facts.name LIKE 'A%'
AND cities.id IS NULL
""", conn)

                  country_name city_name
0  Ashmore and Cartier Islands      None
1                     Akrotiri      None
2                   Antarctica      None
3                 Arctic Ocean      None
4               Atlantic Ocean      None

In [18]:
pd.read_sql_query("""
SELECT cities.name AS capital_name,
       facts.death_rate
FROM cities
LEFT JOIN facts
ON cities.facts_id = facts.id
WHERE cities.capital = 1
""", conn)

     capital_name  death_rate
0      Oranjestad        8.18
1    Saint John'S        5.69
2       Abu Dhabi        1.97
3           Kabul       13.89
4         Algiers        4.31
..            ...         ...
203          Apia        5.32
204       Mbabane       13.56
205         Sanaa        6.28
206        Lusaka       12.67
207        Harare       10.13

[208 rows x 2 columns]

In [20]:
df.shape

(261, 11)

In [21]:
df.columns

Index(['id', 'code', 'name', 'area', 'area_land', 'area_water', 'population',
       'population_growth', 'birth_rate', 'death_rate', 'migration_rate'],
      dtype='object')

In [22]:
df.describe

<bound method NDFrame.describe of       id code            name       area  area_land  area_water    population  \
0      1   af     Afghanistan   652230.0   652230.0         0.0  3.256434e+07
1      2   al         Albania    28748.0    27398.0      1350.0  3.029278e+06
2      3   ag         Algeria  2381741.0  2381741.0         0.0  3.954217e+07
3      4   an         Andorra      468.0      468.0         0.0  8.558000e+04
4      5   ao          Angola  1246700.0  1246700.0         0.0  1.962535e+07
..   ...  ...             ...        ...        ...         ...           ...
256  257   zh  Atlantic Ocean        NaN        NaN         NaN           NaN
257  258   xo    Indian Ocean        NaN        NaN         NaN           NaN
258  259   zn   Pacific Ocean        NaN        NaN         NaN           NaN
259  260   oo  Southern Ocean        NaN        NaN         NaN           NaN
260  261   xx           World        NaN        NaN         NaN  7.256490e+09

     population_growth  birth_rate  death_rate  migration_rate
0                 2.32       38.57       13.89            1.51
1                 0.30       12.92        6.58            3.30
2                 1.84       23.67        4.31            0.92
3                 0.12        8.13        6.96            0.00
4                 2.78       38.78       11.49            0.46
..                 ...         ...         ...             ...
256                NaN         NaN         NaN             NaN
257                NaN         NaN         NaN             NaN
258                NaN         NaN         NaN             NaN
259                NaN         NaN         NaN             NaN
260               1.08       18.60        7.80             NaN

[261 rows x 11 columns]>

In [23]:
df.info

<bound method DataFrame.info of       id code            name       area  area_land  area_water    population  \
0      1   af     Afghanistan   652230.0   652230.0         0.0  3.256434e+07
1      2   al         Albania    28748.0    27398.0      1350.0  3.029278e+06
2      3   ag         Algeria  2381741.0  2381741.0         0.0  3.954217e+07
3      4   an         Andorra      468.0      468.0         0.0  8.558000e+04
4      5   ao          Angola  1246700.0  1246700.0         0.0  1.962535e+07
..   ...  ...             ...        ...        ...         ...           ...
256  257   zh  Atlantic Ocean        NaN        NaN         NaN           NaN
257  258   xo    Indian Ocean        NaN        NaN         NaN           NaN
258  259   zn   Pacific Ocean        NaN        NaN         NaN           NaN
259  260   oo  Southern Ocean        NaN        NaN         NaN           NaN
260  261   xx           World        NaN        NaN         NaN  7.256490e+09

     population_growth  birth_rate  death_rate  migration_rate
0                 2.32       38.57       13.89            1.51
1                 0.30       12.92        6.58            3.30
2                 1.84       23.67        4.31            0.92
3                 0.12        8.13        6.96            0.00
4                 2.78       38.78       11.49            0.46
..                 ...         ...         ...             ...
256                NaN         NaN         NaN             NaN
257                NaN         NaN         NaN             NaN
258                NaN         NaN         NaN             NaN
259                NaN         NaN         NaN             NaN
260               1.08       18.60        7.80             NaN

[261 rows x 11 columns]>